name: SonarQube Analysis

on:
  workflow_dispatch:

jobs:
  sonar:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Run SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=demo-java-app \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_d7750ab754aaab1869b0c15a6f1364094bd98c74
