name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run SonarQube scan
        run: |
          ./gradlew sonar \
          -Dsonar.projectKey=demo-java-app \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=sqp_d7750ab754aaab1869b0c15a6f1364094bd98c74
