name: Dependent Jobs Example

on:
  workflow_dispatch:

jobs:
  job-b:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 2 minutes
        run: sleep 120
        
  job-c:
    runs-on: ubuntu-latest
    #if: false
    steps:
      - name: Job C - Example
        uses: actions/checkout@v4

  job-a:
    needs: [job-b, job-c]
    runs-on: ubuntu-latest
    if: always() && !contains(['failure','cancelled'], needs.job-b.result) && !contains(['failure','cancelled'], needs.job-c.result)
    steps:
      - name: Job A - Runs only if B and C succeeded or skipped
        run: echo "Running job A"
