name: Dependent Jobs Example

on:
  workflow_dispatch:

jobs:
  job-b:
    runs-on: ubuntu-latest
    steps:
      - name: Job B - Example
        run: echo "Running job B"

  job-c:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Job C - Example
        run: echo "Running job C"

  job-a:
    needs: [job-b, job-c]
    runs-on: ubuntu-latest
    if: >
      always() &&
      (needs.job-b.result == 'success' || needs.job-b.result == 'skipped') &&
      (needs.job-c.result == 'success' || needs.job-c.result == 'skipped')
    steps:
      - name: Job A - Runs only if B and C succeeded or skipped
        run: echo "Running job A"
