name: Workflow test Runner Self-Hosted
on:
  workflow_dispatch:
   # - cron: '* * * * *'

jobs:
  runner-pruebas-script:
    runs-on: self-hosted
    steps:
      - name: Prueba runner
        run: echo "------------------el runner esta configurado correctamente---------------"
