name: Dependent Jobs Example

on:
  workflow_dispatch:

jobs:
  job-b:
    runs-on: ubuntu-latest
    steps:
      - name: Job B - Example
        run: echo "Running job B"

  job-c:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Job C - Example
        run: echo "Running job C"

  job-a:
    needs: [job-b, job-c]
    runs-on: ubuntu-latest
    if: always() && needs.job-b.result != 'failure' && needs.job-b.result != 'cancelled' && needs.job-c.result != 'failure' && needs.job-c.result != 'cancelled'
    steps:
      - name: Job A - Runs only if B and C succeeded or skipped
        run: echo "Running job A"
