name: SonarQube Analysis

on:
  workflow_dispatch:

jobs:
  sonar:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Check SonarQube server connectivity
        run: curl -v $SONAR_HOST_URL/api/system/status || true


      - name: Run SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          gradle sonarqube \
            -Dsonar.projectKey=demo-java-app \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
